name: internship_pg_ms_project
description: "StayEasy PG app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2

  # Firebase dependencies added:
  firebase_core: ^2.27.0
  firebase_auth: ^4.19.0
  cloud_firestore: ^4.16.0
  image_picker: ^1.1.1
  firebase_storage: ^11.7.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf

  assets:
    - assets/images/app logo-1.jpg
    - Project_photos/user-avatar-male-5.png
    - Project_photos/user-avatar-female-6.png
    - assets/images/pg1_1.jpg
    - assets/images/pg1_2.jpg
    - assets/images/pg1_3.jpg
    - assets/images/pg1_4.jpg
    - assets/images/pg1_5.jpg
    - assets/images/pg1_6.jpg
